/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JLabel;

/**
 *
 * @author edward
 */
public class InformeV extends javax.swing.JFrame {

    /**
     * Creates new form InformeV
     */
    public InformeV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMayor = new javax.swing.JLabel();
        labelMenor = new javax.swing.JLabel();
        labelPromedio = new javax.swing.JLabel();
        labelInventario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        labelMayor.setText("Precio Mayor: ");

        labelMenor.setText("Precio Menor:");

        labelPromedio.setText("Promedio de Precios: ");

        labelInventario.setText("Valor Inventario: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInventario)
                    .addComponent(labelPromedio)
                    .addComponent(labelMenor)
                    .addComponent(labelMayor))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelMayor)
                .addGap(26, 26, 26)
                .addComponent(labelMenor)
                .addGap(29, 29, 29)
                .addComponent(labelPromedio)
                .addGap(32, 32, 32)
                .addComponent(labelInventario)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeV().setVisible(true);
            }
        });
    }

    public String getInventario() {
        return labelInventario.getText();
    }

    public void setInventario(String inventario) {
        labelInventario.setText(inventario);
    }

    public String getMayor() {
        return labelMayor.getText();
    }

    public void setMayor(String mayor) {
        labelMayor.setText(mayor);
    }

    public String getMenor() {
        return labelMenor.getText();
    }

    public void setMenor(String menor) {
        labelMenor.setText(menor);
    }

    public String getPromedio() {
        return labelPromedio.getText();
    }

    public void setPromedio(String promedio) {
        labelPromedio.setText(promedio);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelMayor;
    private javax.swing.JLabel labelMenor;
    private javax.swing.JLabel labelPromedio;
    // End of variables declaration//GEN-END:variables
}
